### ISSUE TITLE
버그 + 한번 고려해봤으면 좋을 것들

### ISSUE THREAD

**Issue by reeon-limg** [crispizza/vacance#22]
1.  처음 메리스노우에 들어가면 관리소가 이상한 곳에 있음. '설정'버튼을 누르면 원래 자리로 돌아감.
2.  '보관함' 누르는 순간 아무것도 안됨.
3.  편집모드가 아닐때는 건물 밑에 초록색 장판이 안보여야 함.
4. 언니 왈 : "대사가 나오고 있을때 터치하면 대사 전체가 한번에 다 나왔으면 좋겠다. 꾹 누르고 있는걸로는 모자람. "
5. 건물 살때 챠르릉 하는 사운드이펙트 소리가 좀 더 컸으면 좋겠음.

**Comment by reeon-limg** [comment]
6. 핸드폰 돌렸을때 화면 돌아갔으면 좋겠음. (<-이거는 해도 안해도 상관없음)
7. 뒤로 버튼 눌렀을때 종료창이 떴으면 좋겠음. (<- 이것도 해도 안해도 상관없음)

**Comment by crispizza** [comment]
오토세이브 기능을 연습하느라 해놨는데, 처음 실행시에 로드되는 값이 초기화되어있지 않아서 일어나는 버그 라고 추정됨. 오토세이브 기능 제거하니까 원활히 재생됨. 다른이슈들은 밤에 한번 볼께.

**Comment by crispizza** [comment]
1,2,3번 이슈 오토세이브로 해결
4번은 일단 구현해 보고 나은걸 사용하거나, 병행 (말풍선 눌렀을때는 한문장이 다 나오고, 바깥쪽 눌렀을때는 빠르게 한다던지)을 고려해볼께. 어차피 한번보는 튜토리얼인데 또로로로 문장이 나오는게 귀여워서.
5. 수정함.
6,7 . 어떻게 하는지 모르는데 찾아보겠음. 안드로이드 디바이스 관련 이슈라서.

**Comment by reeon-limg** [comment]
이거 알람도 뜨네 좋다! 4번 의견은 나도 동의해. 또로로로 나오는게 귀여워
