### ISSUE TITLE
3/9 수정사항

### ISSUE THREAD

**Issue by reeon-limg** [crispizza/vacance#28]
1. 말풍선에서 대사가 또도도도 나오다가 말풍선안이든 밖이든 아무데나 터치하면 전체문장이 완성되고, 또 터치하면 다음 대사로 넘어가되 다시 또도도도 나오게 할 수 있어?
(현재 : 또도도도 하다가 말풍선 안을 터치하면 전체문장이 완성되는데, 또 터치하면 다음문장이 그냥 전체문장으로 완성되어서 나옴.)
그게 가능하면 그 기능만 놔두고, 꾹 누르고 있을때 빠르게 넘어가는 기능은 없애는게 좋을거같아.

2.  건물 살때 동전소리 뒤에 건물짓는 소리까지 나는거 빼는게 좋을듯.
내가 원하는 이미지 : 상점에서 건물을 사고 첫 배치할때 동전소리만 난다 -> 배치직후 공사장이미지가 뜬다 -> 공사장을 터치할때 (즉시완공하겟냐는 팝업창이 뜨면서) 건물짓는 소리만 난다.

**Comment by crispizza** [comment]
1,2번 수정완료
